### ISSUE TITLE
KeyboardLayout notification not working reliable

### ISSUE THREAD

**Issue by Iomegan** [Clipy/Sauce#1]
Hi,

When I switch the input source in the menu bar from  QWERTY to Dvorak `selectedKeyboardInputSourceChanged()` is often not being called. And then it seems to lag behind one change. Thus `currentKeyCode(by key: Key) -> CGKeyCode?`return the wrong keyCode. I can not recognise a patterns, seems random to me at the moment.

Can anyone confirm this behaviour?

**Comment by Econa77** [comment]
@Iomegan Sorry for the delay in response. I was able to reproduce this problem.

I solved this problem with #2 . If the problem recurs, please reopen the issue 👍
